#!/usr/bin/env python3
"""
Upload leads to the website cache.
Run this after main.py generates leads.

Usage:
    python upload_leads.py

Requirements:
    - Set LEADS_UPLOAD_API_KEY environment variable (same as in Vercel)
    - Run main.py first to generate smb_marketing_leads.csv
"""

import csv
import json
import os
import requests
from dotenv import load_dotenv

load_dotenv()

# Configuration
API_URL = "https://www.ishaangpta.com/api/upload-leads"
CSV_FILE = "smb_marketing_leads.csv"
LOCATION = "Greater Los Angeles Area"

def convert_category(category_str: str) -> str:
    """Convert CSV category to API category (small/medium/large)"""
    if not category_str:
        return 'small'

    cat = category_str.strip().lower()

    # Handle the category values from main.py
    if '≤100' in category_str or '<=100' in cat or cat == 'small':
        return 'small'
    elif '101-250' in category_str or '101' in cat or cat == 'medium':
        return 'medium'
    elif '251' in category_str or '251+' in category_str or cat == 'large':
        return 'large'

    return 'small'  # Default

def get_category_from_size(company_size: str) -> str:
    """Convert company size string to category (small/medium/large)"""
    if not company_size or company_size.lower() == 'unknown':
        return 'small'  # Default to small if unknown

    # Try to extract numbers from the size string
    import re
    numbers = re.findall(r'\d+', company_size)

    if not numbers:
        return 'small'

    # Use the largest number found (usually the upper bound of a range)
    max_employees = max(int(n) for n in numbers)

    if max_employees <= 100:
        return 'small'
    elif max_employees <= 250:
        return 'medium'
    else:
        return 'large'

def read_leads_from_csv(filepath: str) -> list:
    """Read leads from the CSV file generated by main.py"""
    leads = []

    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Skip leads without a contact name AND email
            contact_name = row.get('Contact Name', '').strip()
            contact_email = row.get('Contact Email', '').strip()
            if not contact_name or not contact_email:
                continue

            # Parse name into first/last
            name_parts = contact_name.split(' ', 1)
            first_name = name_parts[0] if name_parts else ''
            last_name = name_parts[1] if len(name_parts) > 1 else ''

            # Determine category - prefer the Category column from CSV
            company_size = row.get('Company Size', '')
            csv_category = row.get('Category', '')

            if csv_category:
                category = convert_category(csv_category)
            else:
                category = get_category_from_size(company_size)

            lead = {
                'firstName': first_name,
                'lastName': last_name,
                'title': row.get('Contact Title', ''),
                'companyName': row.get('Company Name', ''),
                'email': row.get('Contact Email', ''),
                'website': row.get('Website', ''),
                'location': row.get('City/Neighborhood', ''),
                'companySize': company_size,
                'category': category.lower() if category else 'small',
                'evidence': row.get('Evidence', '')
            }
            leads.append(lead)

    return leads

def upload_leads(leads: list, location: str, api_key: str) -> bool:
    """Upload leads to the website API"""
    headers = {
        'Content-Type': 'application/json',
        'X-API-Key': api_key
    }

    payload = {
        'location': location,
        'leads': leads
    }

    try:
        response = requests.post(API_URL, json=payload, headers=headers)
        result = response.json()

        if response.status_code == 200 and result.get('success'):
            print(f"Successfully uploaded {len(leads)} leads!")
            print(f"Stats: {result.get('stats', {})}")
            return True
        else:
            print(f"Error uploading leads: {result.get('error', 'Unknown error')}")
            return False
    except Exception as e:
        print(f"Failed to upload: {e}")
        return False

def main():
    # Check for API key
    api_key = os.getenv('LEADS_UPLOAD_API_KEY')
    if not api_key:
        print("Error: LEADS_UPLOAD_API_KEY environment variable is not set.")
        print("Add it to your .env file or set it in your environment.")
        return

    # Check if CSV file exists
    if not os.path.exists(CSV_FILE):
        print(f"Error: {CSV_FILE} not found.")
        print("Run main.py first to generate leads.")
        return

    # Read leads from CSV
    print(f"Reading leads from {CSV_FILE}...")
    leads = read_leads_from_csv(CSV_FILE)

    if not leads:
        print("No leads with contact names found in CSV.")
        return

    # Count by category
    small = sum(1 for l in leads if l['category'] == 'small')
    medium = sum(1 for l in leads if l['category'] == 'medium')
    large = sum(1 for l in leads if l['category'] == 'large')

    print(f"Found {len(leads)} leads with contact names:")
    print(f"  - Small (<=100 employees): {small}")
    print(f"  - Medium (101-250 employees): {medium}")
    print(f"  - Large (251+ employees): {large}")

    # Upload to API
    print(f"\nUploading to {API_URL}...")
    success = upload_leads(leads, LOCATION, api_key)

    if success:
        print("\nDone! The website will now show these leads.")
        print("Visit: https://www.ishaangpta.com/ai-tools/lead-gen")

if __name__ == "__main__":
    main()
